"use client";

import { useEffect,useState } from "react";
import Link from "next/link";

type Meta={recommendedAction?:string;confidence?:number;extractedQuestion?:string|null;extractedObjection?:string|null;referralContact?:string|null;returnDate?:string|null;suggestedResponse?:string|null;revisitAt?:string|null};
type Lead={id:number;businessName:string|null;domain:string;email:string|null;status:string;replyStatus:string|null;replySummary:string|null;lastReplyAt:string|null;revisitAt?:string|null;activities:Array<{metadata?:Meta}>;outreachMessages:Array<{id:number;kind:string;sequenceNumber:number;subject:string;bodyText:string;status:string;sentAt:string|null}>;contacts?:Array<{type:string;value:string;role:string|null;source:string|null}>};
function priority(status:string|null){if(status==="interested"||status==="booking_intent")return{label:"Critical",cls:"bg-red-500/15 text-red-300"};if(["question","objection","referral"].includes(status??""))return{label:"High",cls:"bg-amber-500/15 text-amber-300"};if(["not_now","out_of_office","wrong_person"].includes(status??""))return{label:"Medium",cls:"bg-sky-500/15 text-sky-300"};return{label:"Normal",cls:"bg-zinc-700 text-zinc-300"};}

export default function InboxPage(){
 const[leads,setLeads]=useState<Lead[]>([]);const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[resolving,setResolving]=useState<Set<number>>(new Set());const[message,setMessage]=useState<string|null>(null);
 async function load(){setLoading(true);try{const res=await fetch("/api/inbox/actions",{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error??"Failed to load action center");setLeads(data.leads??[]);}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function sync(){setSyncing(true);setMessage(null);try{const res=await fetch("/api/inbox/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({limit:100})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Reply sync failed");setMessage(`Checked ${data.processed??0} active threads.`);await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setSyncing(false);}}
 async function resolve(id:number){setResolving(p=>new Set(p).add(id));try{const res=await fetch(`/api/inbox/${id}/resolve`,{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error??"Resolve failed");setLeads(p=>p.filter(l=>l.id!==id));}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setResolving(p=>{const n=new Set(p);n.delete(id);return n;});}}
 return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-4 py-8"><div className="mb-8 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Action Center</h1><p className="mt-1 text-sm text-zinc-400">Replies requiring operator attention. Automated sequences stop or pause according to reply intent.</p></div><div className="flex gap-2"><button onClick={sync} disabled={syncing} className="rounded bg-indigo-700 px-4 py-2 text-sm disabled:opacity-50">{syncing?"Syncing…":"Sync Gmail replies"}</button><Link href="/automation" className="rounded border border-zinc-700 bg-zinc-800 px-4 py-2 text-sm">Automation</Link></div></div>
 {message&&<div className="mb-4 rounded border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm">{message}</div>}
 {loading?<div className="py-12 text-center text-zinc-400">Loading replies…</div>:leads.length===0?<div className="rounded-xl border border-zinc-800 bg-zinc-900 p-10 text-center text-zinc-400">No prospect replies require attention.</div>:<div className="space-y-4">{leads.map(lead=>{const meta=lead.activities?.[0]?.metadata??{};const p=priority(lead.replyStatus);return <section key={lead.id} className="rounded-xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/leads/${lead.id}`} className="text-lg font-semibold hover:text-indigo-300">{lead.businessName||lead.domain}</Link><div className="text-sm text-zinc-500">{lead.domain} · {lead.email??"No current email"}</div></div><div className="flex gap-2 text-xs"><span className={`rounded px-2 py-1 ${p.cls}`}>{p.label}</span><span className="rounded bg-emerald-500/15 px-2 py-1 text-emerald-300">{lead.replyStatus?.replaceAll("_"," ")??lead.status}</span></div></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4"><div className="text-xs font-semibold uppercase text-zinc-500">Reply summary</div><p className="mt-2 text-sm leading-6 text-zinc-300">{lead.replySummary??"—"}</p>{meta.extractedQuestion&&<div className="mt-4"><div className="text-xs uppercase text-zinc-500">Question</div><p className="mt-1 text-sm text-zinc-200">{meta.extractedQuestion}</p></div>}{meta.extractedObjection&&<div className="mt-4"><div className="text-xs uppercase text-zinc-500">Objection</div><p className="mt-1 text-sm text-zinc-200">{meta.extractedObjection}</p></div>}{meta.referralContact&&<div className="mt-4"><div className="text-xs uppercase text-zinc-500">Referral</div><p className="mt-1 text-sm text-zinc-200">{meta.referralContact}</p></div>}</div><div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4"><div className="text-xs font-semibold uppercase text-zinc-500">Recommended action</div><p className="mt-2 text-sm leading-6 text-zinc-300">{meta.recommendedAction??"Review the Gmail thread."}</p>{meta.suggestedResponse&&<div className="mt-4"><div className="text-xs uppercase text-zinc-500">Suggested response · review before sending</div><div className="mt-2 whitespace-pre-wrap rounded border border-zinc-800 bg-zinc-900 p-3 text-sm leading-6 text-zinc-300">{meta.suggestedResponse}</div></div>}{(meta.returnDate||meta.revisitAt||lead.revisitAt)&&<div className="mt-4 text-xs text-zinc-500">Resume/revisit: {new Date(meta.revisitAt??lead.revisitAt??meta.returnDate!).toLocaleString()}</div>}</div></div>
 <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-zinc-500">Last reply: {lead.lastReplyAt?new Date(lead.lastReplyAt).toLocaleString():lead.replyStatus==="out_of_office"?"Out-of-office recorded":"—"} · Sequence messages: {lead.outreachMessages.length}{meta.confidence!=null?` · ${Math.round(meta.confidence*100)}% classification confidence`:""}</div><button onClick={()=>resolve(lead.id)} disabled={resolving.has(lead.id)} className="rounded bg-zinc-700 px-3 py-2 text-sm disabled:opacity-50">{resolving.has(lead.id)?"Resolving…":"Mark handled"}</button></div></section>})}</div>}
 </div></main>;
}
