"use client";

import { useEffect, useState } from "react";

type RateRow = { key: string; contacted: number; replied: number; positive: number; meetings?: number; won?: number; replyRate: number; positiveRate: number; meetingRate?: number; winRate?: number };
type Analytics = {
  totals: { contactedLeads:number; messagesSent:number; replies:number; interested:number; meetings:number; wins:number; replyRate:number; interestedRate:number; meetingRate:number; winRate:number };
  ai: { calls:number; failed:number; inputTokens:number; outputTokens:number; estimatedCost:number; costPerContactedLead:number; costPerReply:number; byModel:Array<{model:string;calls:number;inputTokens:number;outputTokens:number;estimatedCost:number}> };
  byNiche: RateRow[]; byKeyword: RateRow[]; byAngle: RateRow[]; byPriority: RateRow[];
  byProblem: Array<{key:string;contacted:number;replied:number;positive:number;replyRate:number;positiveRate:number}>;
  followupPerformance: Array<{sequenceNumber:number;label:string;sent:number;repliesAttributed:number;attributedReplyRate:number}>;
};

function Stat({ label, value, sub }: { label:string; value:string|number; sub?:string }) {
  return <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-4"><div className="text-xs uppercase tracking-wide text-zinc-500">{label}</div><div className="mt-1 text-2xl font-semibold text-white">{value}</div>{sub && <div className="mt-1 text-xs text-zinc-500">{sub}</div>}</div>;
}

function Table({ title, rows }: { title:string; rows:RateRow[] }) {
  return <section className="rounded-lg border border-zinc-800 bg-zinc-900"><div className="border-b border-zinc-800 px-4 py-3"><h2 className="font-semibold text-white">{title}</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Segment</th><th className="px-4 py-3">Contacted</th><th className="px-4 py-3">Replies</th><th className="px-4 py-3">Reply rate</th><th className="px-4 py-3">Positive</th><th className="px-4 py-3">Positive rate</th></tr></thead><tbody className="divide-y divide-zinc-800">{rows.slice(0,20).map(row=><tr key={row.key}><td className="max-w-md px-4 py-3 text-zinc-200">{row.key}</td><td className="px-4 py-3 text-zinc-400">{row.contacted}</td><td className="px-4 py-3 text-zinc-400">{row.replied}</td><td className="px-4 py-3 text-zinc-200">{row.replyRate}%{row.contacted < 5 && <span className="ml-2 text-xs text-amber-500">small sample</span>}</td><td className="px-4 py-3 text-zinc-400">{row.positive}</td><td className="px-4 py-3 text-zinc-200">{row.positiveRate}%</td></tr>)}</tbody></table></div></section>;
}

export default function AnalyticsPage() {
  const [data,setData]=useState<Analytics|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{try{const res=await fetch("/api/analytics/summary",{cache:"no-store"});const text=await res.text();const body=text?JSON.parse(text):{};if(!res.ok)throw new Error(body.error??"Analytics request failed");setData(body)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}})()},[]);
  if(loading)return <div className="min-h-screen bg-zinc-950 p-8 text-zinc-400">Loading analytics…</div>;
  if(error||!data)return <div className="min-h-screen bg-zinc-950 p-8 text-red-300">{error??"No analytics data"}</div>;
  return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-7xl px-4 py-8"><div className="mb-8"><h1 className="text-2xl font-bold">Analytics</h1><p className="mt-1 text-sm text-zinc-400">Learn which prospects, problems and outreach strategies actually produce replies and opportunities.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Contacted leads" value={data.totals.contactedLeads}/><Stat label="Reply rate" value={`${data.totals.replyRate}%`} sub={`${data.totals.replies} replies`}/><Stat label="Interested rate" value={`${data.totals.interestedRate}%`} sub={`${data.totals.interested} interested`}/><Stat label="Meeting rate" value={`${data.totals.meetingRate}%`} sub={`${data.totals.meetings} meetings+`}/><Stat label="Messages sent" value={data.totals.messagesSent}/><Stat label="Wins" value={data.totals.wins} sub={`${data.totals.winRate}% of contacted`}/><Stat label="AI cost" value={`$${data.ai.estimatedCost.toFixed(4)}`} sub={`${data.ai.calls} calls · ${data.ai.failed} failed`}/><Stat label="AI cost / reply" value={data.totals.replies ? `$${data.ai.costPerReply.toFixed(4)}` : "—"} sub={`$${data.ai.costPerContactedLead.toFixed(4)} / contacted lead`}/></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><Table title="By niche" rows={data.byNiche}/><Table title="By priority score" rows={data.byPriority}/><Table title="By outreach angle" rows={data.byAngle}/><Table title="By keyword" rows={data.byKeyword}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-lg border border-zinc-800 bg-zinc-900"><div className="border-b border-zinc-800 px-4 py-3"><h2 className="font-semibold">Problem categories</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Problem</th><th className="px-4 py-3">Contacted</th><th className="px-4 py-3">Reply</th><th className="px-4 py-3">Positive</th></tr></thead><tbody className="divide-y divide-zinc-800">{data.byProblem.slice(0,20).map(row=><tr key={row.key}><td className="px-4 py-3 text-zinc-200">{row.key}</td><td className="px-4 py-3 text-zinc-400">{row.contacted}</td><td className="px-4 py-3">{row.replyRate}%</td><td className="px-4 py-3">{row.positiveRate}%</td></tr>)}</tbody></table></div></section>
      <section className="rounded-lg border border-zinc-800 bg-zinc-900"><div className="border-b border-zinc-800 px-4 py-3"><h2 className="font-semibold">Follow-up effectiveness</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Touch</th><th className="px-4 py-3">Sent</th><th className="px-4 py-3">Replies attributed</th><th className="px-4 py-3">Rate</th></tr></thead><tbody className="divide-y divide-zinc-800">{data.followupPerformance.map(row=><tr key={row.sequenceNumber}><td className="px-4 py-3 text-zinc-200">{row.label}</td><td className="px-4 py-3 text-zinc-400">{row.sent}</td><td className="px-4 py-3 text-zinc-400">{row.repliesAttributed}</td><td className="px-4 py-3">{row.attributedReplyRate}%</td></tr>)}</tbody></table></div></section></div>
    <section className="mt-6 rounded-lg border border-zinc-800 bg-zinc-900 p-4"><h2 className="font-semibold">AI usage by model</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs uppercase text-zinc-500"><tr><th className="py-2">Model</th><th>Calls</th><th>Input tokens</th><th>Output tokens</th><th>Recorded cost</th></tr></thead><tbody>{data.ai.byModel.map(row=><tr key={row.model} className="border-t border-zinc-800"><td className="py-2 text-zinc-200">{row.model}</td><td>{row.calls}</td><td>{row.inputTokens.toLocaleString()}</td><td>{row.outputTokens.toLocaleString()}</td><td>${row.estimatedCost.toFixed(4)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-zinc-500">Cost figures reflect values recorded on AI jobs. If a model call has no stored estimated cost, token totals remain accurate but dollar cost will be understated.</p></section>
  </div></main>;
}
